// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oedwnexadnohlaypcemi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZHduZXhhZG5vaGxheXBjZW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjUzNjUsImV4cCI6MjA2NTU0MTM2NX0.GpVm4nh3QcLAaVFzjNgySYuxC8nvLYiA_31XJtVVTFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);